# Generated by Django 3.0.3 on 2020-02-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_to_picture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagram',
            name='pronunciation',
            field=models.CharField(default='', max_length=5),
        ),
    ]
